// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuranGuide.Maui.Infrastructure;

#nullable disable

namespace QuranGuide.Maui.Infrastructure.Migrations
{
    [DbContext(typeof(QuranDbContext))]
    partial class QuranDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuranGuide.Maui.Core.DataTransferObjects.UserPreferences", b =>
                {
                    b.Property<bool>("AutoPlayAudio")
                        .HasColumnType("boolean");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("boolean");

                    b.Property<int>("FontSize")
                        .HasColumnType("integer");

                    b.Property<bool>("OfflineMode")
                        .HasColumnType("boolean");

                    b.Property<string>("SelectedEdition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("QuranGuide.Maui.Core.Models.Ayah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EditionId")
                        .HasColumnType("integer");

                    b.Property<int>("HizbQuarter")
                        .HasColumnType("integer");

                    b.Property<int>("Juz")
                        .HasColumnType("integer");

                    b.Property<int>("Manzil")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("NumberInSurah")
                        .HasColumnType("integer");

                    b.Property<int>("Page")
                        .HasColumnType("integer");

                    b.Property<int>("Ruku")
                        .HasColumnType("integer");

                    b.Property<int>("SajdaNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SajdaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SurahId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SurahId", "NumberInSurah", "EditionId");

                    b.ToTable("Ayahs");
                });

            modelBuilder.Entity("QuranGuide.Maui.Core.Models.DownloadedContent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DownloadedContent");
                });

            modelBuilder.Entity("QuranGuide.Maui.Core.Models.Edition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Editions");
                });

            modelBuilder.Entity("QuranGuide.Maui.Core.Models.Hadith", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookSlug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChapterId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnglishNarrator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HadithArabic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HadithEnglish")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HadithNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadingArabic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadingEnglish")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Volume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hadiths");
                });

            modelBuilder.Entity("QuranGuide.Maui.Core.Models.Surah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnglishNameTranslation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HizbQuarter")
                        .HasColumnType("integer");

                    b.Property<int>("Juz")
                        .HasColumnType("integer");

                    b.Property<int>("Manzil")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfAyahs")
                        .HasColumnType("integer");

                    b.Property<int>("Page")
                        .HasColumnType("integer");

                    b.Property<string>("RevelationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ruku")
                        .HasColumnType("integer");

                    b.Property<int>("SajdaNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SajdaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Surahs");
                });
#pragma warning restore 612, 618
        }
    }
}
